### ISSUE TITLE
Is the distinction between constructors and methods necessary?

### ISSUE THREAD

**Issue by oscarlvp** [Tanaht/VNVProject#2]
In the code that handles byte code instructions, you make a difference between constructors and methods. It is really needed? Both, CtConstructor and CtMethod inherit from CtBehavior. Moreover, in your code it seems that you are doing the same for both.

**Comment by Tanaht** [comment]
No it's not necessary anymore, I've made this distinction because when I was constructing a ControlFlow object the related constructor from javassist looks like that: ControlFlow​(CtMethod method).

But I figured out there was another constructor: ControlFlow​(CtClass ctclazz, MethodInfo minfo) that doesnt rely on what kind of CtBehavior it is.

So it was fixed in https://github.com/Tanaht/VNVProject/commit/e3606d464714162b627f0e540318b9d049b6bd6b
